# Generated by Django 3.0.8 on 2023-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Webpages',
        ),
    ]
